export const fundraiserFields = [
    "fundraiserName",
    "deliveryDate",
    "formattedDate",
    "formattedTime",
    "reminderDate",
    "Formatted Delivery Date",
    "Formatted Delivery Time",
    "cookDate",
    "status",
    "daysUntilDelivery",
    "daysUntilCook",
    "deliveryAddress",
    "deliveryCity",
    "deliveryState",
    "deliveryZip",
    "deliveryNotes",
    "products",
    // "productRecords",
    "customerPremiumPrice",
    "customerStandardPrice",
    "customerButtPrice",
    "customerHamPrice",
    "customerTurkeyPrice",
    "customerSaucePrice",
    "firehousePremiumPrice",
    "firehouseStandardPrice",
    "firehouseButtPrice",
    "firehouseHamPrice",
    "firehouseTurkeyPrice",
    "firehouseSaucePrice",
    "priority",
    "orders",
    "Supporter Email (from orders)",
    "orderTotals",
    "totalRevenue",
    "organization",
    "contactFirstName",
    "contactLastName",
    "contactFullName",
    "contactEmail",
    "contactPhone",
    "contactPreferredMethod",
    "contactAddress",
    "contactAddressLine2",
    "contactCity",
    "contactState",
    "contactZip",
    // "contactIsBilling",
    // "billingContactFullName",
    // "billingEmail",
    // "billingPhone",
    "recordID",
    "sellers",
    "Email (from sellers)",
    "allOrders",
    "orderCount",
    // "promoSocialPdf",
    // "promoSocialPng",
    // "standardImage",
    // "premiumImage",
    // "buttImage",
    // "hamImage",
    // "turkeyImage",
    // "sauceImage",
    // "completeRegistrationURL",
    "inviteSellersURL",
    "guardianIDs",
    "Email (from guardianIDs)",
    // "profitWatcherHTML",
    // "profitWatcherURL",
    // "deliveryWatcherHTML",
    // "thankYouForCreatingFundraiserHTML",
    // "thankYouForCreatingFundraiserURL",
    // "editDeliveryAddressURL",
    "standardCount",
    "premiumCount",
    "buttCount",
    "hamCount",
    "turkeyCount",
    "sauceCount",
    "providerFee",
    "ccFees",
    "organizationProceeds",
    "suppliers",
    "Users (from suppliers)",
    "Emails (from suppliers)",
    "Users",
    "Email (from Users)",
    "Last modified time",
    "Welcome Email Sent",
    // "Welcome Email Subject",
    // "Welcome Email Body",
    // "customOrderConfirmationSubject",
    // "customDeliveryDetailsParagraph",
    // "customContactDetailsParagraph",
    // "FundraiserProductRecords",
    // "isTest?",
    // "testOrders",
    // "Administrators",
    // "email (from Administrators)",
];

export const userFields = [
    "Email",
    "emailToLowerCase",
    "userRoles",
    "userID",
    "adminRecords",
    "admin fundraiserIDs",
    "sellerRecords",
    "RecordID (from Fundraiser) (from sellerRecords)",
    "Fundraiser (from sellerRecords)",
    "providerRecords",
    "Fundraisers (from Providers)",
    "guardianRecords",
    "Active Fundraiser (from guardianRecords)",
    "recordID (from Active Fundraiser) (from guardianRecords)",
    "organizerRecords",
    "recordID (from organizerRecords)",
    "allFundraisers",
]

export const guardianFields = [
    "GuardianID",
    "FirstName",
    "LastName",
    "FullName",
    "Email",
    "Phone",
    "AddressLine1",
    "AddressLine2",
    "City",
    "State",
    "Zip",
    "MailingList OptIn",
    "Active Fundraiser",
    "recordID (from Active Fundraiser)",
    "sellerIDs",
    "PendingSeller",
    "Fundraiser (from sellerIDs)",
    "Seller Usernames",
    "UpdateSellerURL",
    "CreateSellerURL",
    "Users",
];

export const sellerFields = [
    "recordID",
    "Nickname",
    "MinorStatus",
    "findID",
    "CreatedBy",
    "Email",
    "Phone",
    "AddressLine1",
    "AddressLine2",
    "City",
    "State",
    "Zip",
    "Fundraiser",
    // "standardImage (from Fundraiser)",
    // "premiumImage (from Fundraiser)",
    // "buttImage (from Fundraiser)",
    // "hamImage (from Fundraiser)",
    // "turkeyImage (from Fundraiser)",
    // "sauceImage (from Fundraiser)",
    "productRecords (from Fundraiser)",
    "RecordID (from Fundraiser)",
    "Organization (from Fundraiser)",
    "Primary Phone (from Fundraiser)",
    "Primary Contact First Name (from Fundraiser)",
    "Primary Contact Last Name (from Fundraiser)",
    "Products (from Fundraiser)",
    "ProductsToDisplay",
    "ProductsHTML",
    "ProductRecords",
    "Description (from ProductRecords)",
    "photoURL (from ProductRecords)",
    "orderIDs",
    "Total Price (from Orders)",
    "Supporters",
    "Last modified",
    "SellerGuardian",
    "Email (from SellerGuardian)",
    "Phone (from SellerGuardian)",
    "AddressLine1 (from SellerGuardian)",
    "AddressLine2 (from SellerGuardian)",
    "City (from SellerGuardian)",
    "Zip (from SellerGuardian)",
    "State (from SellerGuardian)",
    "Guardian FullName",
    "Contact Email",
    "Contact Phone",
    "Contact Address",
    "Contact Address Line 2",
    "Contact City",
    "Contact State",
    "Contact Zip",
    "SellerStorefrontHTML",
    "SellerStorefrontURL",
    "Link to Order From This Seller",
    "CreateGuardianURL",
    "AddAnotherSellerHTML",
    "ThankYouForRegisteringHTML",
    "CreateAnotherSellerFormURL",
    "RedirectURL",
    "Total Orders",
    "Total Sales Volume",
    "AddAnotherSellerURL",
    "ThankYouForRegisteringURL",
    "Users",
    "Orders copy",
];

export const orderFields = [
    "Order ID",
    "Date",
    "Fundraiser",
    "customContactDetailsParagraph (from Fundraiser)",
    "customOrderConfirmationSubject (from Fundraiser)",
    "customDeliveryDetailsParagraph (from Fundraiser)",
    "formattedTime (from Fundraiser)",
    "formattedDate (from Fundraiser)",
    "deliveryState (from Fundraiser)",
    "contactPhone (from Fundraiser)",
    "contactFullName (from Fundraiser)",
    "deliveryAddress (from Fundraiser)",
    "deliveryCity (from Fundraiser)",
    "deliveryDate (from Fundraiser)",
    "organization (from Fundraiser)",
    "FundraiserName (from Fundraiser)",
    "Seller",
    "Username (from Seller)",
    "ProductsToDisplay",
    "Supporter First Name",
    "Supporter Last Name",
    "Supporter Full Name",
    "Supporter Email",
    "emailCopy",
    "Supporter Phone",
    "Payment Method",
    // "Payment Image",
    "PremiumQty",
    "PremiumPrice",
    "StandardQty",
    "StandardPrice",
    "ButtQty",
    "ButtPrice (from Fundraiser)",
    "HamQty",
    "HamPrice (from Fundraiser)",
    "TurkeyQty",
    "TurkeyPrice (from Fundraiser)",
    "SauceQty",
    "SaucePrice (from Fundraiser)",
    "Total Price",
    "ProductNameForStripe",
    "QuantityForStripe",
    "Status",
    "PlaceAnOrderURL",
    "Supporters",
    "Last modified",
    "ThankYouForYourOrderHTML",
    "ThankYouForYourOrderURL",
    "Order Summary",
    "Supporter AddressLine1",
    "Supporter AddressLine2",
    "Supporter City",
    "Supporter State",
    "Supporter Zip",
    "Supporter MailingList OptIn",
    "Order Confirmation Sent",
    "orderDetailsParagraph",
    "deliveryDetailsParagraph",
    "contactDetailsParagraph",
    "emailClosing",
    "Order Confirmation Subject",
    "Order Confirmation Body",
    "Products",
    "Products 2",
    "Products 3",
    "Products 4"
];

export const supporterFields = [
    "Name",
    "First Name",
    "Last Name",
    "Phone",
    "Email",
    "MailingList OptIn",
    "Address Line 1",
    "Address Line 2",
    "City",
    "State",
    "Zip",
    "Sellers",
    "Username (from Sellers)",
    "Orders",
    "Orders copy",
];

export const providerFields = [
    "RecordID",
    "Supplier Name",
    "Fundraisers",
    "recordID (from Fundraisers)",
    "Totals Paid (from Orders) (from Fundraisers)",
    "Sellers (from Fundraisers)",
    "ButtCount (from Fundraisers)",
    "HamCount (from Fundraisers)",
    "TurkeyCount (from Fundraisers)",
    "SauceCount (from Fundraisers)",
    "Firehouse Fee (from Fundraisers)",
    "CC Fees (from Fundraisers)",
    "Organization Proceeds (from Fundraisers)",
    "OrderCount (from Fundraisers)",
    "Butts",
    "Hams",
    "Turkeys",
    "Sauces",
    "Total Orders",
    "Completed Profits",
    "Active Profits",
    "Confirmed Profits , Pending Delivery",
    "Cancelled Profits",
    "Inquiries",
    "Users",
    "ReferenceProducts",
    "FunderaiserProductRecords",
];

export const referenceProductFields = [
    "Name",
    "Description",
    "photoURL",
    "Photo",
    "Firehouse Price",
    "Provider",
    "RecordID (from Provider)",
    "Fundraisers",
    "Sellers",
    "Fundraisers 2",
    "recordID"
];
