export const fundraiserFields = [
    "fundraiserName",
    "deliveryDate",
    "formattedDate",
    "formattedTime",
    "reminderDate",
    "Formatted Delivery Date",
    "Formatted Delivery Time",
    "cookDate",
    "status",
    "daysUntilDelivery",
    "daysUntilCook",
    "deliveryAddress",
    "deliveryCity",
    "deliveryState",
    "deliveryZip",
    "deliveryNotes",
    "products",
    "productRecords",
    "customerPremiumPrice",
    "customerStandardPrice",
    "customerButtPrice",
    "customerHamPrice",
    "customerTurkeyPrice",
    "customerSaucePrice",
    "firehousePremiumPrice",
    "firehouseStandardPrice",
    "firehouseButtPrice",
    "firehouseHamPrice",
    "firehouseTurkeyPrice",
    "firehouseSaucePrice",
    "priority",
    "orders",
    "Supporter Email (from orders)",
    "orderTotals",
    "totalRevenue",
    "organization",
    "contactFirstName",
    "contactLastName",
    "contactFullName",
    "contactEmail",
    "contactPhone",
    "contactPreferredMethod",
    "contactAddress",
    "contactAddressLine2",
    "contactCity",
    "contactState",
    "contactZip",
    "contactIsBilling",
    "billingContactFullName",
    "billingEmail",
    "billingPhone",
    "recordID",
    "sellers",
    "Email (from sellers)",
    "allOrders",
    "orderCount",
    "promoSocialPdf",
    "promoSocialPng",
    "standardImage",
    "premiumImage",
    "buttImage",
    "hamImage",
    "turkeyImage",
    "sauceImage",
    "completeRegistrationURL",
    "inviteSellersURL",
    "guardianIDs",
    "Email (from guardianIDs)",
    "profitWatcherHTML",
    "profitWatcherURL",
    "deliveryWatcherHTML",
    "thankYouForCreatingFundraiserHTML",
    "thankYouForCreatingFundraiserURL",
    "editDeliveryAddressURL",
    "standardCount",
    "premiumCount",
    "hamCount",
    "turkeyCount",
    "sauceCount",
    "providerFee",
    "ccFees",
    "organizationProceeds",
    "suppliers",
    "Users (from suppliers)",
    "Users",
    "Email (from Users)",
    "Last modified time",
    "Welcome Email Sent",
    "Welcome Email Subject",
    "Welcome Email Body",
    "FundraiserProductRecords",
    "isTest",
    "testOrders",
    "Administrators",
    "email (from Administrators)",
];

export const userFields = [
    "Email",
    "userRoles",
    "userID",
    "adminRecords",
    "admin fundraiserIDs",
    "sellerRecords",
    "RecordID (from Fundraiser) (from sellerRecords)",
    "Fundraiser (from sellerRecords",
    "providerRecords",
    "Fundraisers (from Providers)",
    "guardianRecords",
    "Active Fundraiser (from guardianRecords)",
    "recordID (from Active Fundraiser) (from guardianRecords)",
    "organizerRecords",
    "recordID (from organizerRecords)",
    "allFundraisers",
]

export const productsFields = [
    "recordID",
    "fundraiser",
    "productName",
    "Provider",
    "providerPrice",
    "customerPrice",
    "paidOrders",
    "total"
]